// Generated by CoffeeScript 1.12.5
(function() {
  this.cambiar = function() {
    var element;
    element = document.getElementById('caja');
    if (element.className === 'estilo1') {
      return element.className = 'estilo2';
    } else {
      return element.className = 'estilo1';
    }
  };

}).call(this);
