// Generated by CoffeeScript 1.12.5
(function() {
  this.mensaje = function(valor) {
    switch (valor.id) {
      case '1':
        return document.getElementById('caja').innerHTML = "Haz hecho click al cuadro # " + valor.id;
      case '2':
        return document.getElementById('caja').innerHTML = "Haz hecho doble click al cuadro # " + valor.id;
      case '3':
        return document.getElementById('caja').innerHTML = "Haz entrado al cuadro # " + valor.id;
      case '4':
        return document.getElementById('caja').innerHTML = "Haz salido del cuadro # " + valor.id;
    }
  };

}).call(this);
