// Generated by CoffeeScript 1.12.5
(function() {
  $(function() {
    $('p#elemento').text('hola!!!');
    return $('button').click(function() {
      return $('section').html('<h2>Agregando HTML</h2>');
    });
  });

}).call(this);
