// Generated by CoffeeScript 1.12.5
(function() {
  var mostrar, ocultar;

  this.mostrar_ocultar = function() {
    var boton;
    boton = document.getElementById('boton');
    if (boton.textContent === 'mostrar') {
      mostrar();
      return boton.textContent = 'ocultar';
    } else {
      ocultar();
      return boton.textContent = 'mostrar';
    }
  };

  mostrar = function() {
    return document.getElementById('caja').style.display = 'block';
  };

  ocultar = function() {
    return document.getElementById('caja').style.display = 'none';
  };

}).call(this);
