// Generated by CoffeeScript 1.12.5
(function() {
  var var1, var2;

  var1 = 'first word';

  var2 = 'second word';

  document.getElementById('elemento').textContent = var1 + " " + var2;

  console.log("#-->{var1}");

}).call(this);
